USE BTdb
INSERT Users (UserName, Pasword) VALUES ('Кожихов', '0051982')
INSERT Users (UserName, Pasword) VALUES ('Околович', '1')
INSERT Users (UserName, Pasword) VALUES ('Денисенко', '2')
INSERT Users (UserName, Pasword) VALUES ('Байкова', '3')
INSERT Users (UserName, Pasword) VALUES ('Баранова', '4')

INSERT Ranks (Rank) VALUES ('рядовой')
INSERT Ranks (Rank) VALUES ('ефрейтор')
INSERT Ranks (Rank) VALUES ('мл.сержант')
INSERT Ranks (Rank) VALUES ('сержант')
INSERT Ranks (Rank) VALUES ('ст.сержант')
INSERT Ranks (Rank) VALUES ('старшина')
INSERT Ranks (Rank) VALUES ('прапощик')
INSERT Ranks (Rank) VALUES ('ст.прапорщик')
INSERT Ranks (Rank) VALUES ('мл.лейтенант')
INSERT Ranks (Rank) VALUES ('лейтенант')
INSERT Ranks (Rank) VALUES ('ст.лейтенант')
INSERT Ranks (Rank) VALUES ('капитан')
INSERT Ranks (Rank) VALUES ('майор')
INSERT Ranks (Rank) VALUES ('подполковник')
INSERT Ranks (Rank) VALUES ('полковник')
INSERT Ranks (Rank) VALUES ('генерал-майор')


INSERT Staff (RankID, LastName, FirstName, Patronymic, UserID) VALUES (1, 'Иванов', 'Никита', 'Сергеевич', 1)
INSERT Staff (RankID, LastName, FirstName, Patronymic, UserID) VALUES (10, 'Пушкин', 'Зигмунд', 'Феликсовач', 1)
INSERT Staff (RankID, LastName, FirstName, Patronymic, UserID) VALUES (14, 'Мезенцев', 'Петр', 'Николаевич', 3)
INSERT Staff (RankID, LastName, FirstName, Patronymic, UserID) VALUES (3, 'Соколов', 'Никита', 'Иванович', 3)
INSERT Staff (RankID, LastName, FirstName, Patronymic, UserID) VALUES (10, 'Ильин', 'Александр', 'Петрович', 4)
INSERT Staff (RankID, LastName, FirstName, Patronymic, UserID) VALUES (13, 'Шиш', 'Владимир', 'Яковлевич', 1)
INSERT Staff (RankID, LastName, FirstName, Patronymic, UserID) VALUES (12, 'Харчишин', 'Ярослав', 'Александрович', 1)
INSERT Staff (RankID, LastName, FirstName, Patronymic, UserID) VALUES (10, 'Сухаленцев', 'Дмитрий', 'Сергеевич', 2)
INSERT Staff (RankID, LastName, FirstName, Patronymic, UserID) VALUES (9, 'Лотенков', 'Илья', 'Андреевич', 2)
INSERT Staff (RankID, LastName, FirstName, Patronymic, UserID) VALUES (13, 'Бурдо', 'Максим', 'Сергеевич', 2)
INSERT Staff (RankID, LastName, FirstName, Patronymic, UserID) VALUES (11, 'Рощин', 'Алексей', 'Александрович', 2)
INSERT Staff (RankID, LastName, FirstName, Patronymic, UserID) VALUES (1, 'Якимов', 'Роман', 'Павлович', 5)
INSERT Staff (RankID, LastName, FirstName, Patronymic, UserID) VALUES (5, 'Седиков', 'Денис', 'Михайлович', 5)
INSERT Staff (RankID, LastName, FirstName, Patronymic, UserID) VALUES (7, 'Ананенко', 'Никлоай', 'Иванович', 2)
INSERT Staff (RankID, LastName, FirstName, Patronymic, UserID) VALUES (8, 'Романюк', 'Алексей', 'Игоревич', 4)
INSERT Staff (RankID, LastName, FirstName, Patronymic, UserID) VALUES (15, 'Симкин', 'Сергей', 'Олегович', 3)


INSERT BusinessTripPurposes (ExpenditureItem, Purpose) VALUES (2026, 'Перевозка личного состава')
INSERT BusinessTripPurposes (ExpenditureItem, Purpose) VALUES (2026, 'Сопровождение личного состава')
INSERT BusinessTripPurposes (ExpenditureItem, Purpose) VALUES (2026, 'Уточнение документов')
INSERT BusinessTripPurposes (ExpenditureItem, Purpose) VALUES (2026, 'Согласование документов')
INSERT BusinessTripPurposes (ExpenditureItem, Purpose) VALUES (2026, 'Получение имущества')
INSERT BusinessTripPurposes (ExpenditureItem, Purpose) VALUES (2026, 'Оказание помощи')
INSERT BusinessTripPurposes (ExpenditureItem, Purpose) VALUES (4026, 'Соревнования')
INSERT BusinessTripPurposes (ExpenditureItem, Purpose) VALUES (4026, 'Занятия по специальной подготовке')
INSERT BusinessTripPurposes (ExpenditureItem, Purpose) VALUES (4026, 'Сборы по специальной подготовке')
INSERT BusinessTripPurposes (ExpenditureItem, Purpose) VALUES (4026, 'Обучение вождению техники')
INSERT BusinessTripPurposes (ExpenditureItem, Purpose) VALUES (4146, 'Курсы повышения квалификации')


INSERT TransitRates (Rate, BeginDate, EndDate) VALUES (2.55, '2019.03.19', '2019.12.31')
INSERT TransitRates (Rate, BeginDate, EndDate) VALUES (2.70, '2020.01.01', '2019.12.31')
INSERT TransitRates (Rate, BeginDate) VALUES (2.9, '2021.01.01')


INSERT LocalityTypes (Type) VALUES ('областной центр')
INSERT LocalityTypes (Type) VALUES ('районный центр')
INSERT LocalityTypes (Type) VALUES ('иной населенный пункт')

INSERT Localities(LocalityTypeID, Name) VALUES (1, 'Минск')
INSERT Localities(LocalityTypeID, Name) VALUES (1, 'Брест')
INSERT Localities(LocalityTypeID, Name) VALUES (1, 'Витебск')
INSERT Localities(LocalityTypeID, Name) VALUES (1, 'Гомель')
INSERT Localities(LocalityTypeID, Name) VALUES (1, 'Гродно')
INSERT Localities(LocalityTypeID, Name) VALUES (1, 'Могилев')
INSERT Localities(LocalityTypeID, Name) VALUES (2, 'Барановичи')
INSERT Localities(LocalityTypeID, Name) VALUES (2, 'Бобруйск')
INSERT Localities(LocalityTypeID, Name) VALUES (2, 'Марьина Горка')
INSERT Localities(LocalityTypeID, Name) VALUES (2, 'Старые Дороги')
INSERT Localities(LocalityTypeID, Name) VALUES (2, 'Новогрудок')
INSERT Localities(LocalityTypeID, Name) VALUES (2, 'Жлобин')
INSERT Localities(LocalityTypeID, Name) VALUES (2, 'Рогачев')
INSERT Localities(LocalityTypeID, Name) VALUES (2, 'Ивье')
INSERT Localities(LocalityTypeID, Name) VALUES (3, 'Колодищи')
INSERT Localities(LocalityTypeID, Name) VALUES (3, 'Лапичи')
INSERT Localities(LocalityTypeID, Name) VALUES (3, 'Прудок')
INSERT Localities(LocalityTypeID, Name) VALUES (3, 'Красный Берег')

INSERT BusinessTripStates (Summary) VALUES ('издан приказ о командировке')
INSERT BusinessTripStates (Summary) VALUES ('получен авансовый отчет')
INSERT BusinessTripStates (Summary) VALUES ('авансовый отчет возвращен на доработку')
INSERT BusinessTripStates (Summary) VALUES ('введен авансовый отчет')
INSERT BusinessTripStates (Summary) VALUES ('произведен расчет командировочных')
